# Use Ubuntu as the base image
FROM ubuntu:22.04

# Install build tools and dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    gdb\
    wget \
    curl \
    git \
    flex \
    bison \
    pkg-config \
    autoconf \
    automake \
    libtool \
    libnet1-dev \
    clang \
    gcc \
    g++ \
    make \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Set Clang as the default compiler for ASan
# ENV CC=clang
# ENV CXX=clang++

# Build and install libpcap 1.10.4
RUN mkdir /test
WORKDIR /test
RUN wget https://www.tcpdump.org/release/libpcap-1.10.4.tar.gz && \
    tar xvf libpcap-1.10.4.tar.gz && \
    cd libpcap-1.10.4 && \
    CC=clang CFLAGS="-g -O0 -fsanitize=address -fno-omit-frame-pointer" \
    LDFLAGS="-fsanitize=address" \
    ./configure && \
    make -j$(nproc) && \
    make install

# Build and install tcpdump 4.99.4
RUN wget https://www.tcpdump.org/release/tcpdump-4.99.4.tar.gz && \
    tar xvf tcpdump-4.99.4.tar.gz && \
    cd tcpdump-4.99.4 && \
    CC=clang CFLAGS="-g -O0 -fsanitize=address -fno-omit-frame-pointer" \
    LDFLAGS="-fsanitize=address" \
    ./configure && \
    make -j$(nproc) && \
    make install

#Set ASan runtime environment
ENV ASAN_OPTIONS=detect_leaks=1:halt_on_error=1:abort_on_error=1:symbolize=1

# Create directory for test files
# RUN mkdir /test
WORKDIR /test

COPY test-poc.c /test/test-poc.c
# COPY test-poc.py /test/test-poc.py
# RUN gcc /test/tcpdump-poc.c -o /test/tcpdump-poc
# Clean up
# RUN rm -rf /tmp/libpcap-1.10.4*
# RUN rm -rf /tmp/tcpdump-4.99.4*

# Default command: show tcpdump version
CMD ["/bin/bash"]
