# Use Ubuntu 16.04 as base
FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive

# Install build tools and dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    clang \
    wget \
    tar \
    xz-utils \
    libx11-dev \
    libxext-dev \
    libxmu-dev \
    libxpm-dev \
    libxt-dev \
    && rm -rf /var/lib/apt/lists/*

# Download and install fig2dev 3.2.8a (latest available source)
WORKDIR /test
COPY docker/fig2dev-3.2.7b.tar.xz .
#As it is xz file not gzip file so we have to use -J option => -xvJf instead of -xvzf
RUN tar -xvJf fig2dev-3.2.7b.tar.xz && \
    cd fig2dev-3.2.7b && \
    ./configure CC="clang -O2 -fno-omit-frame-pointer -g -fsanitize=address" CXX="clang++ -O2 -fno-omit-frame-pointer -g -fsanitize=address" && \
    make && make install

COPY fig2dev/fig2dev_groundtruth_PoCs/fig2dev_box_crash  /test/fig2dev_box_crash
COPY test-poc.fig /test/test-poc.fig
CMD ["/bin/bash"]
