FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive


ENV CFLAGS="-g -O1 -fsanitize=address,undefined"
ENV CXXFLAGS="-g -O1 -fsanitize=address,undefined"
ENV LDFLAGS="-fsanitize=address,undefined"
ENV ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer
ENV ASAN_OPTIONS=detect_leaks=1:abort_on_error=1:symbolize=1

WORKDIR /usr/src


# Install dependencies

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git wget ca-certificates unzip python3 python3-dev \
    autoconf automake libtool m4 pkg-config \
    gcc g++ clang llvm libfuzzer-14-dev \
    libc6-dev zlib1g-dev \
 && rm -rf /var/lib/apt/lists/*


RUN git clone https://github.com/liblouis/liblouis.git /usr/src/liblouis && \
    cd /usr/src/liblouis && \
    git fetch --tags --quiet && \
    git checkout -q v3.21.0

WORKDIR /usr/src/liblouis


# Build & Install Liblouis with ASan/UBSan

RUN ./autogen.sh && \
    ./configure --prefix=/usr/local CC=clang CXX=clang++ CFLAGS="${CFLAGS}" CXXFLAGS="${CXXFLAGS}" LDFLAGS="${LDFLAGS}" && \
    make -j"$(nproc)" && \
    make install


CMD ["/bin/bash"]
